agile-lab-dev/GIS.Lib

- src/main/scala/it/agilelab/bigdata/gis/domain/managers/GeometryMembershipInfoManager.scala
- src/test/scala/it/agilelab/bigdata/gis/domain/loader/ContainmentRelationBtwGeometriesSpec.scala
- src/test/scala/it/agilelab/bigdata/gis/domain/loader/GeoCategoryMembershipSpec.scala
Introduce new API for check if a list of point is within a list of geometry.
This improves performance.
Closes #15
> [#15] Introduce a multipoint category membership info capability

- pom.xml
Dependencies update due to remote url change
> updated "geo" repository

- src/main/scala/it/agilelab/bigdata/gis/domain/loader/OSMAdministrativeBoundariesLoader.scala
- src/test/resources/reference.conf
- src/test/scala/it/agilelab/bigdata/gis/domain/loader/OSMManagerSpec.scala
Added following section on config file:
```
{
boundary {
administrative: {
value: 4
level: 2
}
}
```
Closes #20
> added config boundary.administrative section and manage it on scala class

- pom.xml
- publish snapshot on `oss.jfrog` repo
No
No
No
Closes #28
> [#28] add snapshotRepository

- src/main/resources/reference.conf
- src/main/scala/it/agilelab/bigdata/gis/core/utils/Configuration.scala
- src/main/scala/it/agilelab/bigdata/gis/core/utils/ConfigurationReader.scala
- src/main/scala/it/agilelab/bigdata/gis/core/utils/ValidationUtils.scala
- src/main/scala/it/agilelab/bigdata/gis/domain/graphhopper/AlgorithmType.scala
- src/main/scala/it/agilelab/bigdata/gis/domain/graphhopper/GraphHopperManager.scala
- src/main/scala/it/agilelab/bigdata/gis/domain/loader/GraphHopperConfiguration.scala
- src/main/scala/it/agilelab/bigdata/gis/domain/loader/OSMManager.scala
- src/main/scala/it/agilelab/bigdata/gis/domain/loader/OSMManagerConfiguration.scala
- src/main/scala/it/agilelab/bigdata/gis/domain/loader/ReverseGeocoder.scala
- src/main/scala/it/agilelab/bigdata/gis/domain/loader/RouteMatcher.scala
- src/test/resources/reference.conf
- src/test/scala/it/agilelab/bigdata/gis/core/GraphHopperSpec.scala
- src/test/scala/it/agilelab/bigdata/gis/domain/loader/OSMManagerConfigurationSpec.scala
- src/test/scala/it/agilelab/bigdata/gis/domain/loader/OSMManagerSpec.scala
- Refactored `GraphHopperManager` into a case class for testability purpose
- Refactored `OSMManager` into a case class for testability purpose
- Added configurations for both Manager for validating configuration parameters
- Created two traits for mixing behaviours into Managers for testability
No
No
No
Closes #30
> [#30] pass configuration to managers

- src/test/scala/it/agilelab/bigdata/gis/core/GraphHopperSpec.scala
[#37] fix GraphHopperSpec tests
- Fixed two `GraphHopperTest` 
- Now we can run `mvn test` without any issue
No
No
No
Closes #37
> Fix GraphHopperSpec tests

- pom.xml
- src/main/scala/it/agilelab/bigdata/gis/core/manager/Manager.scala
- src/main/scala/it/agilelab/bigdata/gis/core/utils/Logger.scala
- src/main/scala/it/agilelab/bigdata/gis/core/utils/ValidationUtils.scala
- src/test/resources/log4j.properties
- src/test/resources/simplelogger.properties
- src/test/scala/it/agilelab/bigdata/gis/core/GraphHopperSpec.scala
- Removed log4j dependency
- Added slf4j api and simple logger to allowing logging when is used from other libraries
- Removed hardcoded pom version and added properties 
Closes #39
> Removed log4j dependency 

- src/main/scala/it/agilelab/bigdata/gis/domain/loader/OSMAdministrativeBoundariesLoader.scala
- src/main/scala/it/agilelab/bigdata/gis/domain/managers/PathManager.scala
While looking at this error, I thought we can improve it to be more informative.
> Improve exception's message on unrecognized administrative level

- .gitignore
- src/main/scala/it/agilelab/bigdata/gis/core/utils/ConfigurationProperties.scala
- src/main/scala/it/agilelab/bigdata/gis/core/utils/ObjectPickler.scala
- src/main/scala/it/agilelab/bigdata/gis/domain/configuration/IndexManagerConfiguration.scala
- src/main/scala/it/agilelab/bigdata/gis/domain/managers/IndexManager.scala
- src/test/resources/reference-osm-file-index.conf
- src/test/scala/it/agilelab/bigdata/gis/domain/loader/OSMManagerSpec.scala
- Serialize OSM index for faster app startup
Closes #62
> Serialize OSM index for faster app startup

- pom.xml
- Exclude Jackson core and databind dependencies
Closes #74
> Exclude Jackson core and databind dependencies

- pom.xml
- Bump Scala from 2.11.2 to 2.11.12
Closes #76
> Bump Scala from 2.11.2 to 2.11.12

- src/main/scala/it/agilelab/gis/domain/loader/ReverseGeocoder.scala
- src/main/scala/it/agilelab/gis/domain/managers/OSMManager.scala
- src/main/scala/it/agilelab/gis/domain/models/ReverseGeocodingResponse.scala
- src/test/scala/it/agilelab/gis/domain/loader/OSMManagerSpec.scala
- src/test/scala/it/agilelab/gis/domain/loader/ReverseGeocoderSpec.scala
- Support specifying reverse geocoding indices to query
Closes #81
> Support specifying reverse geocoding indices to query

- src/main/scala/it/agilelab/gis/domain/configuration/GraphHopperConfiguration.scala
- src/main/scala/it/agilelab/gis/domain/graphhopper/CustomPathDetails.scala
- src/main/scala/it/agilelab/gis/domain/graphhopper/Edge.scala
- src/main/scala/it/agilelab/gis/domain/graphhopper/EnrichEdge.scala
- src/main/scala/it/agilelab/gis/domain/graphhopper/GraphHopperManager.scala
- src/main/scala/it/agilelab/gis/domain/graphhopper/MatchedRoute.scala
- src/test/scala/it/agilelab/gis/core/GraphHopperSpec.scala
- Improve accuracy of distance between points.
- Add a bunch of tests of our graph hopper manager.
> Improve accuracy of distance between points

- src/main/scala/it/agilelab/gis/domain/managers/IndexManager.scala
**Bug fixes**
- Remove incorrect log message
Fixes #64
> Fix bad log message

- src/main/scala/it/agilelab/gis/domain/models/GeometriesOperations.scala
- src/test/scala/it/agilelab/gis/domain/model/GeometriesOperationsSuite.scala
- Added contains() functionality given two geometries
- Added unit tests
#88
> [#88] "contains" functionality

- src/main/scala/it/agilelab/gis/domain/loader/ShapeFileReader.scala
Discard geometry null when load administrative boundary
> [#95] - NPE when load boundary with null geometry

- src/main/scala/it/agilelab/gis/core/utils/WktConverter.scala
- src/main/scala/it/agilelab/gis/domain/managers/GeometriesOperations.scala
- src/test/scala/it/agilelab/gis/core/WktConverterSuite.scala
- src/test/scala/it/agilelab/gis/domain/manager/GeometriesOperationsSuite.scala
- Added a reader able to convert a WKT String into a Geometry object
- Generalized method contains() with the wkt stirngs
- Updated and added tests
#93
> [#93] Generic Input for method in GeometriesOperation

- src/main/scala/it/agilelab/gis/core/utils/DistanceUtils.scala
- src/main/scala/it/agilelab/gis/domain/managers/GeometriesOperations.scala
- src/test/scala/it/agilelab/gis/domain/manager/GeometriesOperationsSuite.scala
- Added computeDistance() functionality to compute distance between geometries
- Added unit tests
Related issue
#87
> [#87] distance between two geometry

- src/main/scala/it/agilelab/gis/core/model/geometry/Circle.scala
- src/main/scala/it/agilelab/gis/core/utils/WKTReaderRich.scala
- src/test/scala/it/agilelab/gis/core/GeometryDistanceSpec.scala
Added a method to compute the distance between a generic point and the border of the circle
Closes #101
> [#101] Added distance method to circle class

- src/main/scala/it/agilelab/gis/domain/loader/OSMAdministrativeBoundariesLoader.scala
- src/test/resources/reference.conf
Added postal code when loading OSM boundaries
Closes #103
> Added PostalCode as a parameter

- pom.xml
- src/main/scala/it/agilelab/gis/core/utils/GeoJsonConverter.scala
- src/main/scala/it/agilelab/gis/core/utils/GeometryTypeOperations.scala
- src/main/scala/it/agilelab/gis/domain/managers/GeometriesOperations.scala
- src/test/scala/it/agilelab/gis/core/GeoJsonConverterSuite.scala
- src/test/scala/it/agilelab/gis/core/WktConverterSuite.scala
- src/test/scala/it/agilelab/gis/domain/manager/GeometriesOperationsSuite.scala
**Feature and improvements**
- Added a JsonImplicit object which convert Geometry objects into a json format and vice versa
- Added related test class 
#97
> [#97] Generic Output for method in GeometriesOperation

- src/main/scala/it/agilelab/gis/core/model/geometry/Circle.scala
- src/test/scala/it/agilelab/gis/core/GeometryDistanceSpec.scala
Distance is no more computed used the euclidean formula
Closes #107
> [#107] circle distance harvesine formula

- src/main/scala/it/agilelab/gis/core/utils/WKTReaderRich.scala
WKT Read instantiate a new reader for every wkt string received
Closes #114
> Reset of wkt reader

- pom.xml
Version of `xmlgraphics` changed: v2.3 -> v.2.6
Closes #121
> feature: Fix vulnerability on xmlgraphics dependency

- src/main/scala/it/agilelab/gis/domain/managers/PoiManager.scala
- src/main/scala/it/agilelab/gis/domain/models/GeometryWithDistance.scala
- src/main/scala/it/agilelab/gis/domain/models/OSMPoi.scala
- src/main/scala/it/agilelab/gis/domain/spatialList/SpatialList.scala
- src/main/scala/it/agilelab/gis/domain/spatialOperator/KNNQueryMem.scala
- src/test/scala/it/agilelab/gis/domain/loader/PoiManagerSpec.scala
Created a new method spatialQueryWithMaxDistanceIntegrated in KNNQueryMem class that returns geometries and their respective distances from query center
Closes #128
> [#128] Return distance in spatial query

- src/main/scala/it/agilelab/gis/domain/graphhopper/GraphHopperManager.scala
N/A
N/A
N/A
Return correct speed limit information
Closes #140
> fix wrong speed limit

- build.sbt
- src/main/scala/it/agilelab/gis/core/encoder/CarFlagEncoderEnrich.scala
New mapping for speed limits aligned with Italian limits
Closes #142
> [#142] Change defaultSpeedLimit
